### ISSUE TITLE
Contributors y sus funciones

### ISSUE THREAD

**Issue by pablortsal** [Coffee-WIP/coffeewip-organization#1]
La idea es decidir quienes van a ser los primeros contributors para el proyecto y cuales son los puntos donde quieren aportar.
Id poniendo todos los interesados dentro del stack en que puntos quieren participar

- Gestión PM/PO
- Diseño UX/UI
- Desarrollo Frontend
- Desarrollo Backend
- Infraestructura (Local)
- Infraestructura (Cloud)
- Testing QA

**Comment by pablortsal** [comment]
Yo me ofrezco para Frontend

**Comment by chempogonzalez** [comment]
Yo para Frontend y el diseño

**Comment by JoseJPR** [comment]
Yo me ofrezco para Backend y Diseño.

**Comment by JoseJPR** [comment]
@pablortsal he añadido unos puntos más al listado de funciones. :)

**Comment by jucastil** [comment]
En cuanto haya algo de codigo yo preparo un docker nginx o similar para correrlo local en pruebas y ver como se ve

**Comment by JoseJPR** [comment]
@jucastil eso correspondería, si no me confundo a: Infraestructura (Local) :)

**Comment by jucastil** [comment]
@JoseJPR la idea de meter todo en un docker es que no importa donde corra... aunque al final tendrá que correr en algún sitio. En principio yo podría lanzar una instancia con vuestro diseño (un docker compose?) y hacerla visible con ngrok o similar. No necesito acceso a Infraestructura (Local). Solo un repositorio. Si os gusta entonces solo habría que lanzar el docker en otro sitio que corra dockers. Como AWS... vamos, Infraestructura (Cloud)

**Comment by Anexon** [comment]
A mi me interesa colaborar en Front+Back+Infraestructura

**Comment by pablortsal** [comment]
Si os parece luego actualizo el readme de este proyecto y pongo a los colaboradores por categorías =)

**Comment by pablortsal** [comment]
Cierro esta issue ,ha medida que entren nuevos se les puede plantear que quieren trabajar y yo los añado al readme
