### ISSUE TITLE
Selección Logotipo CoffeeWIP

### ISSUE THREAD

**Issue by chempogonzalez** [Coffee-WIP/coffeewip-organization#10]
Buenas a todos!

Después de estas semanas que estamos todos un poco menos activos con estas calores, veranito, etc... He sacado un huequillo para poder presentaros algunas propuestas para el logotipo. Me gustaría que votarais por la que más os convence. Por aquí os dejo las propuestas. (Se aceptan propuestas para mejorar algún logo si es el más elegido)

En todas he intentado mantener un poco el concepto de coffee wip mezclando esa parte de programación con el café, así como también en las propuestas 3 y 4 he jugado con las formas para crear ese "café" y que aparezca las siglas "C" y "W" de CoffeeWIP. Por ejemplo, la propuesta 3, la C forma la taza y la W el líquido del café, así como la propuesta 4 es el concepto de un café visto desde arriba manteniendo esa "c" y "w"

## Propuesta 1
<img width="1060" alt="Captura de pantalla 2020-07-20 a las 22 11 07" src="https://user-images.githubusercontent.com/45340869/87982084-874cf080-cad6-11ea-9dea-382dbc4667e7.png">

## Propuesta 2 
<img width="1089" alt="Captura de pantalla 2020-07-20 a las 22 11 22" src="https://user-images.githubusercontent.com/45340869/87982093-8a47e100-cad6-11ea-98bd-aef492a60b58.png">

## Propuesta 3
<img width="1110" alt="Captura de pantalla 2020-07-20 a las 22 11 37" src="https://user-images.githubusercontent.com/45340869/87982098-8c11a480-cad6-11ea-89be-4dce5a181089.png">

## Propuesta 4
<img width="348" alt="Captura de pantalla 2020-07-20 a las 22 11 45" src="https://user-images.githubusercontent.com/45340869/87982101-8c11a480-cad6-11ea-9476-05241fe9b75b.png">

**Comment by pablortsal** [comment]
Hello! A mi me gusta la propuesta 2.

**Comment by Anexon** [comment]
@chempogonzalez wow, currazo!
**La segunda me gana por ser una imagen muy fácilmente reconocible.**
La primera también me resultan muy atractivas, serían mi segunda opción. Las que son en plano me flipan. Y también me he fijado que después del COVID casi soy capaz de verlas como mascarillas :DDD!
La terceras y cuartas son muy interesantes por la decostrucción, igual viéndolas en un par de días se le pilla cariño. Pero así a priori me quedan más abstractas.

Todas las propuestas tienen su punto, enhorabuena!

**Comment by jucastil** [comment]
Mi voto va por la 2 también. El vaso de papel no es muy ecológico, pero es más moderno que la taza de la propuesta 1. La 4 mola un monton, pero me recuerda a algo, aunque no se a que. Y solo debería de recordar a  CoffeeWIP :-)

**Comment by JoseJPR** [comment]
Buenas a todos!, @chempogonzalez muy currado, enhorabuena! 👍 

Por mi parte voto por la opción número 2, creo que es la que más fácil es de recordar.

Saludos!

**Comment by JoseJPR** [comment]
Cierro la issue por finalización.
