### ISSUE TITLE
Decidir infraestructura del proyecto (Monorepo VS repo por proyecto)

### ISSUE THREAD

**Issue by pablortsal** [Coffee-WIP/coffeewip-organization#2]
Es necesario decidir si monorepo o multiples repos.

**Comment by pablortsal** [comment]
Yo la parte del monorepo por probar me parece guay, pero es verdad que si somos ujnos cuantos trabajando se puede liar bastante , yo optaria por esa si hay alguien en los colaboradores que mas o menos sepa gestionarlo

**Comment by JoseJPR** [comment]
Yo en el caso de monorepo he trabajado en proyectos con front y back en los que he estado yo solo desarrollando, para desarrollo con front y back en equipos siempre ha sido multirepo.

No veo mal poder trabajar en monorepo siempre y cuando no generemos un monolito. A mi parecer y sería mi apuesta tiraría por multirepo y trabajar front por un lado y back por otro lado.

Pensando en un primer momento que las librerías comunes entre front y back podrían ser typescript para tipado, eslint por alineamiento de escritura y jest o cypress para testing y teniendo en cuenta que mi propuesta para la parte de NodeJS será la de trabajar prácticamente sin librerías externas y si directamente con el core yo optaría por **Multirepo**.

:)

**Comment by pablortsal** [comment]
Estoy contigo @JoseJPR  a ver que dicen un par de personas más cerramos tema

**Comment by JoseJPR** [comment]
@Coffee-WIP/web-site-contributors Necesitamos que todos tengan revisado este issue para mañana. Es importante que quede resuelto y con los comentarios que vais oportunos para poder avanzar.

**Comment by chempogonzalez** [comment]
Si, de acuerdo en seguir sin monorepo de momento ya que puede ser un stopper para comenzar bien con esto por la falta de experiencia pero sigo sin verlo una mala opción aunque sí que nos va a generar más trabajo al principio.

**Multirepo** entonces

**Comment by Anexon** [comment]
Por mi parte igual: keep it simple y más para empezar

**Comment by Anexon** [comment]
Yo por mi parte igual. Keep it simple y sobre todo para empezar
