### ISSUE TITLE
Framework Web

### ISSUE THREAD

**Issue by Anexon** [Coffee-WIP/coffeewip-organization#3]
# Framework Web
Para la elección del framework en el que desarrollar de la página web de CoffeeWip tendría en cuenta las siguientes cuestiones:
* Facilidad para el SEO (server side rendering, static sites, etc.).
* Alojamiento. Si utilizamos github pages por ejemplo no tendríamos servidor que nos reindexe las rutas lo cual es un problema para las SPAs.
* Interés en practicar un framework u otro.

Yo por interés y considerando lo anterior propongo la siguiente lista de frameworks para hacer la página, ordenada por preferencia:
* React (NextJS, Gatsby, o react a secas)
* Angular
* Vue
* Ionic

Con la posibilidad de implementar un Design System o cualquier componente adhoc en Stencil.

**Comment by JoseJPR** [comment]
Hola a tod@s,

Yo apostaría por crear componentes con Stencil, trabajar con una base de React y renderizar la solución con NestJS.

Para publicarla y tenerla desplegada con opción a tener router yo tiraría con algo cloud... quizás aquí Vicente nos pueda dar luz :)

**Comment by pablortsal** [comment]
Yo por mi un NestJS puede funcionar bien, tenemos el SSR para poder hacer buen seo y en react mas o menos todo el mundo se apaña. Luego la parte de stencilJS pues igual, podemos crearnos una cuenta en npm y subimos un repo publico con los recursos de desing system de la web y puede quedar rechulon

**Comment by chempogonzalez** [comment]
Buenas, la solución que estais aportando me gusta muhco. Lo único que no me termina de quedar claro es lo de NestJS porque dice @JoseJPR: "base de React y renderizar solución con NestJS". No se si te refieres a NextJS o a usar NestJS en el backend para la API y añadirle ahí con otra cosa/plugin el SSR ?

**Comment by Anexon** [comment]
Ya he iniciado el proyecto en NextJS -> https://github.com/Coffee-WIP/coffeewip-website
Nada algo básico con un par de elementos de ejemplo (routing y elementos), para que en la próxima podamos ir planificando algo más; secciones a implementar, estilos, etc..

@chempogonzalez yo creo que si se refieren a NextJS. Y por cierto, NextJS tiene por defecto [SSR](https://nextjs.org/docs/basic-features/pages#server-side-rendering).

**Comment by pablortsal** [comment]
@Anexon  el projecto, pretende ser solo el front no? para cerrar la issue de mono repo frente a multi repo, es decir hemos tirado por multi repo

**Comment by JoseJPR** [comment]
@chempogonzalez Ha sido una errata, me refería a NextJS que es la librería por antonomasia para React :)

**Comment by pablortsal** [comment]
Pues  si esta el proyecto creado y todos (@JoseJPR , @chempogonzalez ) de acuerdo cierra issue @Anexon

**Comment by chempogonzalez** [comment]
Ok por mi parte!

**Comment by Anexon** [comment]
Se ha comentado en la reunión del martes 30 de junio que siempre que sea conveniente se utilice Stencil para generar componentes propios reutilizables.
