### ISSUE TITLE
Contenido básico de la Web

### ISSUE THREAD

**Issue by Anexon** [Coffee-WIP/coffeewip-organization#4]
El objetivo de la página web es dar a conocer la red de CoffeeWIP para conseguir que un mayor número de personas dedicadas al mundo digital puedan compartir sus experiencias y aprendizajes.

En esta línea la página debería contener:
* Instrucciones sobre cómo colaborar.
* Calendario de charlas; breve resumen, ponente, referencias, etc...
* Referencias a videos y/o recursos de interés generados en CoffeeWIP
* Listado de los perfiles registrados en Slack (los que quieran).
* Listado de ofertas de trabajo facilitadas a CoffeeWIP.
* Referencia a redes sociales para fomentar la difusión.

---
Ideas a futuro:
* Formulario para propuesta de ponencias.
* Formulario para propuesta de patrocinadores.

### Decisiones
* ¿Cómo veis el listado de contenidos?¿Añadiríais algo más para la primera iteración?
* ¿Quién quiere generar los COPYs? (resumen sobre coffeewip, títulos, resumen sobre como colaborar, etc..)

**Comment by JoseJPR** [comment]
@Anexon te doy mi visión por cada punto.

- Instrucciones sobre cómo colaborar. -> Me gusta la propuesta, quizás un botón de acceder al Slack y/o Github y listo.
- Calendario de charlas; breve resumen, ponente, referencias, etc... -> Yo por no comprometernos tanto de cara al exterior por ahora estos temas los manejaría internamente por Slack, como hasta ahora hemos realizado.
- Referencias a videos y/o recursos de interés generados en CoffeeWIP -> Podríamos tirar de la API de Youtube.
- Listado de los perfiles registrados en Slack (los que quieran). -> A mi parecer todos los usuarios que estén en Slack deben de ser mostrados en este listado, es una comunidad OpenSource y a mi parecer debería ser transparente 100%.
- Listado de ofertas de trabajo facilitadas a CoffeeWIP. -> Mostraría los últimos 10 mensajes del canal #jobs.
- Referencia a redes sociales para fomentar la difusión. -> Por ahora tenemos Twitter y Youtube.

Al listado añadiría que has expuesto añadiría:
- Listado de últimas issues generadas desde Github, ganaríamos, a mi parecer, transparencia y podría incentivar al usuario a participar en Github.

**Comment by Anexon** [comment]
@JoseJPR, comparto completamente lo que has añadido. 

Creo que con este "guión" de contenidos se puede empezar a trabajar en una propuesta de diseño de la web y sobre los copies ir trabajándolos sobre la marcha.

Este issue no tenía mucha mayor ambición que definir brevemente esto, lo dejo abierto hasta la próxima reunión por si alguien quiere añadir algo más.

**Comment by JoseJPR** [comment]
@Anexon En nuestra meeting de los martes podemos ver este issue y cerrarlo, creo que estamos cerca.

**Comment by pablortsal** [comment]
Yo creo que con lo que habéis puesto los dos vamos sobrados para la primera iteración, como dice @JoseJPR en la reunión del marte se puede bajar unos cuantos requisitos y vamos ya creando tareas mas concretas

**Comment by chempogonzalez** [comment]
Lo veo perfecto, así tengo ya más la visión de la web y así poder ir tirando con el diseño. Mañana comentamos un poco más por encima y por si alguien tiene ya en mente alguna idea, pues eso que nos llevamos y ayuda más a diseñarlo.

**Comment by Anexon** [comment]
En la última reunión comentamos que para la primera iteración tenemos la información suficiente para empezar.
